pygments: true
relative_permalinks: false
gauges_id: 503c5af6613f5d0f19000027
url: http://daraff.github.io/jsgamewiki
#url: http://localhost:4000
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]